useNodeVersion: 22.15.0
packages:
  - packages/*
  - web/*
  - plugins/*
  - internal/*
ignoredBuiltDependencies:
  - '@bundled-es-modules/glob'
  - sharp
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - esbuild
  - style-dictionary
