name: Checks
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'packages/**'
      - 'apps/**'
      - 'plugins/**'
      - 'biome.jsonc'
jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/gh-setup
      - name: Build
        run: yarn build
      - name: Types
        run: yarn types
      - name: Biome CI
        run: yarn biome ci .
