# https://github.com/changesets/changesets/blob/main/docs/prereleases.md
name: Enter prerelease mode

on:
  workflow_dispatch:
  push:
    branches:
      - next

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Enter prerelease with next tag
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/gh-setup
      - name: Enter prerelease mode for changesets
        if: ${{ hashFiles('.changeset/pre.json') == '' }}
        run: yarn changeset pre enter next
      - name: Commit changes
        if: ${{ hashFiles('.changeset/pre.json') == '' }}
        uses: EndBug/add-and-commit@v9
        with:
          pull: '--rebase --autostash'
          default_author: github_actions
          message: 'ci: 📖 Enter prerelease mode for changesets'
          add: '.'
